# -*- encoding: utf-8 -*-
$:.push File.expand_path("../lib", __FILE__)
require "fix-lame-id3-generated-by-k3b/version"

Gem::Specification.new do |s|
  s.name        = "fix-lame-id3-generated-by-k3b"
  s.version     = FixLameId3GeneratedByK3b::VERSION
  s.authors     = ["Rodrigo Rosenfeld Rosas"]
  s.email       = ["rr.rosas@gmail.com"]
  s.homepage    = "https://github.com/rosenfeld/fix-lame-id3-generated-by-k3b"
  s.summary     = %q{Fix id3 tag encodings generated by lame in K3b}
  #s.description = %q{TODO: Write a gem description}

  s.rubyforge_project = "fix-lame-id3-generated-by-k3b"

  s.files         = `git ls-files`.split("\n")
  #s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.executables   = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
  s.require_paths = ["lib"]

  s.add_runtime_dependency "ruby-mp3info"
end
